
replicaCount: 1

containerPort: 8080

image:
  repository: email
  pullPolicy: IfNotPresent
  tag: "v1"

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "opentelemetry-demo"

service:
  type: ClusterIP
  port: 8080
