---
# Source: opentelemetry-demo/templates/component.yaml
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-frontendproxy
  labels:
    
    opentelemetry.io/name: opentelemetry-demo-frontendproxy
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/component: frontendproxy
    app.kubernetes.io/name: opentelemetry-demo-frontendproxy
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: {{ .Values.service.type}}
  ports:
    - port: {{ .Values.service.port}}
      name: tcp-service
      targetPort: service
  selector:
    
    opentelemetry.io/name: opentelemetry-demo-frontendproxy
