
replicaCount: 1

containerPort: 9099

image:
  repository: 831926618816.dkr.ecr.us-east-1.amazonaws.com/ad
  pullPolicy: IfNotPresent
  tag: "v1"

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "opentelemetry-demo"

service:
  type: ClusterIP
  port: 8080
