
replicaCount: 1

containerPort: 6379

image:
  repository: valkey/valkey:7.2-alpine
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "opentelemetry-demo"

service:
  type: ClusterIP
  port: 6379
