
replicaCount: 1

containerPort: 9092
containerPort01: 9093

image:
  repository: ghcr.io/open-telemetry/demo:1.12.0-kafka
  pullPolicy: IfNotPresent

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "opentelemetry-demo"

service:
  type: ClusterIP
  port: 9092
  port01: 9093
